server:
  # 服务端口
  port: 24803
  # 是否启用响应压缩，默认为 false
  compression:
    enabled: true
    # 启用压缩的最小响应大小（字节），默认为 2048
    min-response-size: 1024
  tomcat:
    # 最大连接数，默认为 10000
    max-connections: 5000
    # 最大线程数，默认为 200
    max-threads: 100
    # 接受队列长度，默认为 100
    accept-count: 200
    # 连接超时时间（毫秒），默认为 20000
    connection-timeout: 30000
    # 长连接的空闲超时时间（毫秒），默认为 20000
    keep-alive-timeout: 30000
    # 最大允许上传的文件大小（字节），默认为 2MB
    max-swallow-size: 10485760
    # 最大允许的单个文件大小（字节），默认为 1MB
    max-file-size: 5242880
    # 最大允许的请求大小（字节），默认为 10MB
    max-request-size: 10485760

spring:
  application:
    name: rss-backend
  profiles:
    active: rss
  web:
    resources:
      static-locations: classpath:/static/
  ############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: false

log:
  path: log/
  encoder: UTF-8
